application: gold-quest
version: 1
runtime: python
api_version: 1

builtins:
- admin_redirect: on
- datastore_admin: on
- appstats: on
- deferred: on

inbound_services:
- channel_presence

handlers:
- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico
- url: /images/goldframe/(.+)
  static_files: images/\1
  upload: images/.+
- url: /stylesheets/goldframe/(.+)
  static_files: stylesheets/\1
  upload: stylesheets/.+
- url: /javascript/goldframe/(.+)
  static_files: javascript/\1
  upload: javascript/.+
- url: /stylesheets/(.+)/(.+)
  static_files: GoldFrame/games/\1/stylesheets/\2
  upload: GoldFrame/games/.+/stylesheets/.+\.css
- url: /javascript/(.+)/(.+)
  static_files: GoldFrame/games/\1/javascript/\2
  upload: GoldFrame/games/.+/javascript/.+\.js
- url: /images/(.+)/(.+)
  static_files: GoldFrame/games/\1/images/\2
  upload: GoldFrame/games/.+/images/.+
- url: /stylesheets/(.+)
  static_files: stylesheets/\1
  upload: stylesheets/.+
- url: /javascript/(.+)
  static_files: javascript/\1
  upload: javascript/.+
- url: /images/(.+)
  static_files: images/\1
  upload: images/.+
- url: /api/.*
  script: main.py
- url: /game/goldquest/.*
  script: GoldFrame/games/goldquest/web.py
- url: /.*
  script: web.py
