application: gold-quest
version: 1
runtime: python
api_version: 1

inbound_services:
- channel_presence

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
- url: /stylesheets
  static_dir: stylesheets
- url: /javascript
  static_dir: javascript
- url: /images
  static_dir: images
- url: /.*
  script: main.py
